Quick Fix question integration test
amtteamheig/amt_project pull request #45
Opened 2020-10-20 19:05 UTC by KurohanaJuri

C'est une version qui marche mais faudra améliorer.Pour l'instant j'ai fait en sort que les tests s'exécuter dans l'ordre alphabetique. Il faudra changer ça, il faut supprimer chaque insertion à la fin de chaque tests

2020-10-22 08:56 UTC, StephaneB1 approved these changes

2020-10-22 11:10 UTC, BPotet requested changes
Tes tests sont déjà présents dans l'autre branch

2020-10-22 11:23 UTC, KurohanaJuri commented
> 
> 
> Tes tests sont déjà présents dans l'autre branch

Ouais parce que je voulais les changement sur l'autre branche

2020-10-23 09:24 UTC, BPotet requested changes

2020-10-23 09:24 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/application/question/QuestionFacade.java
> +        this.userRepository = userRepository;
Stilly why brrrrr

2020-10-23 09:24 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/application/ServiceRegistry.java
> +        questionFacade = new QuestionFacade(questionRepository, userRepository);
Pour les tests, il faudrait plutôt utiliser un userFacade

2020-10-23 09:24 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/application/authentication/AuthenticationFacade.java
> +    public void delete(UserId id){
delete -> remove

2020-10-23 09:24 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/application/question/QuestionFacade.java
> +    public QuestionsDTO getQuestions(QuestionQuery query) {
Créer une deuxième méthode getQuestions() avec rien en paramètre qui findAll()

2020-10-23 13:06 UTC, BPotet approved these changes

2020-10-23 13:06 UTC, merged