Fb add answer to a question
amtteamheig/amt_project pull request #46
Opened 2020-10-21 13:26 UTC by KurohanaJuri

2020-10-22 08:58 UTC, StephaneB1 approved these changes

2020-10-22 11:08 UTC, BPotet requested changes

2020-10-22 11:08 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/application/question/QuestionFacade.java
> +    public QuestionFacade(IQuestionRepository questionRepository, IUserRepository userRepository) {
Pourquoi avoir ajouter le IUserRepository si celui-ci n'est pas utilisé dans le constructeur ?

2020-10-22 11:08 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/application/ServiceRegistry.java
> +        questionFacade = new QuestionFacade(questionRepository, userRepository);
Pourquoi y a userRepository dans le constructeur de la Facade maintenant ?

2020-10-22 11:08 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/application/answer/AnswerFacade.java
> +     * Ask to the DB to insert a answer
Ask to the repository serait plus correct comme commentaire :P C'est pas obligatoirement une base de données derrière

2020-10-22 11:08 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/application/question/QuestionCommand.java
> +    private String username;
Pourquoi l'username et pas l'id ? Bien que le username soit unique, c'est incohérent que la commande soit obligatoirement lié à un username

2020-10-22 11:08 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/application/question/QuestionsDTO.java
> +        private String username;
Même remarque que précédemment, il est plus cohérent de rester avec des ids, il serait tout à fait possible qu'à l'avenir le username soit pas obligatoirement unique

2020-10-22 11:08 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/domain/answer/Answer.java
> +    @Setter(AccessLevel.NONE)
C'est plus cohérent de le faire comme ça, mais j'crois que Answer est la seule classe du package domain qui le fait -> bah soit on change partout, soit on change que là, mais je sais pas si ça a une influence sur le builder notamment pour écrire
```java
AnswerDTO answerGotByDB = ...
Answer answer = Answer.builder().id(answerGotByDB.id())
```

2020-10-22 11:08 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/domain/answer/Answer.java
> +            if(username == null || username.isEmpty()){
Même remarque, plus cohérent d'avoir le UserID

2020-10-22 11:08 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/domain/answer/IAnswerRepository.java
> +    Optional<ArrayList<Answer>> findByQuestionId(QuestionId questionId);
Pourquoi pas List ou Collection ? Pour que ce soit générique :)

2020-10-22 11:08 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/infrastructure/persistence/jdbc/JdbcAnswerRepository.java
> +            statement.setTimestamp(3, creationDate);
setDate devrait marcher également, il faut par contre utiliser java.mysql.Date de souvenir (attention, ça fait que la date, donc si tu veux le temps exact effectivement ça marche pas)

2020-10-22 11:08 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/infrastructure/persistence/jdbc/JdbcQuestionRepository.java
> +                            "            WHERE userName = ?))"
Mais pourquoi username ._. Tu fais une requête interne à un insert avec le fait d'utiliser username

2020-10-22 11:08 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/infrastructure/persistence/jdbc/JdbcQuestionRepository.java
> +                            "       U.userName" +
Rajoute le U.id, au cas où, on en aurait besoin

2020-10-22 11:08 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/infrastructure/persistence/jdbc/JdbcQuestionRepository.java
> +                    "SELECT Q.id           as 'question_id', " +
Pourquoi pas simplement laisser à l'utilisateur que c'est à lui de gérer d'avoir deux facades si il en a besoin, par exemple, dans le cas de l'affichage du détails de la question, d'avoir :
- QuestionFacade
- AnswerFacade
Et d'avoir sur AnswerFacade, un getAnswers(AnswerQuery query) qui va voir si query.questionId != null et donc va retourner toutes les réponses de la question, au lieu d'avoir une requête grosse qui contient beaucoup d'information inutile. Après, on est sur du Web, on est pas sur de la 4G où on a besoin de faire moins de requêtes.

2020-10-22 11:08 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/infrastructure/persistence/jdbc/JdbcQuestionRepository.java
> +                    .username(rs.getString("userName"))
Pareil, pourquoi userName xD Tu te fais chier xD

2020-10-22 11:08 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/ui/web/question/handler/AnswerHandler.java
> +        for (Cookie cookie : cookies) {
Pourquoi pas utiliser la session directement au lieu des cookies ?

2020-10-22 11:08 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/ui/web/question/handler/NewQuestionRequestHandler.java
> +                .username(currentUserDTO.getUsername())
le vote, il a disparu :thinking: ? Je sais qu'on avait fait débat sur on le laisse ou non

2020-10-22 11:08 UTC, BPotet commented on src/main/webapp/WEB-INF/views/question.jsp
> +<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
Qu'est-ce-que ça ?

2020-10-22 11:08 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/application/answer/AnswerFacade.java
> +
Il manque un test if l'id de la commande n'existe pas ou si le username n'existe pas (mais dans le cas-là  où tu passes à nouveau sur le userId bah si le userId existe)

2020-10-22 11:08 UTC, BPotet commented on src/test/java/ch/heigvd/amt/mvcProject/application/question/QuestionFacadeTestIT.java
> +    public void A_GetQuestionWhenEmptyReturnEmptyList() {
Le @Order du coup marche :)

2020-10-22 11:08 UTC, BPotet commented on src/test/java/ch/heigvd/amt/mvcProject/application/answer/AnswerFacadeTestIT.java
> +
Il manque quelque test notamment sur le fait que la questionId ou le answerId est incorrect. Tu ne testes pas également si le remove de AnswerFacade remove bien la Answer

2020-10-22 11:08 UTC, BPotet commented on src/test/java/ch/heigvd/amt/mvcProject/application/question/QuestionFacadeTestIT.java
> +
T'as oublié de clean tes tests et à mon avis à nouveau il manque des tests si l'authorId / username existe

2020-10-22 11:08 UTC, BPotet commented on src/test/java/ch/heigvd/amt/mvcProject/domain/answer/AnswerTest.java
> +                .id(new AnswerId())
le id est de toute façon généré, pourquoi le faire ici

2020-10-22 11:08 UTC, BPotet commented on src/test/resources/arquillian.xml
> +            <property name="wlpHome">/home/chauying/Bureau/Dev/AMT/Project/AMT_Project/target/liberty/wlp</property>
Ouais alors 'faudra faire un jouli gitignore

2020-10-22 11:23 UTC, KurohanaJuri commented on src/main/java/ch/heigvd/amt/mvcProject/application/question/QuestionCommand.java
> +    private String username;
Ouais je me suis rendu compte ce matin que c'était pas smart

2020-10-22 11:27 UTC, KurohanaJuri commented on src/main/java/ch/heigvd/amt/mvcProject/infrastructure/persistence/jdbc/JdbcAnswerRepository.java
> +            statement.setTimestamp(3, creationDate);
On veut l'heure aussi non ? Sur la DB c'est un DATETIME, si c'est le cas c'est un timestamp => https://stackoverflow.com/a/6874232

2020-10-22 11:33 UTC, KurohanaJuri commented on src/main/java/ch/heigvd/amt/mvcProject/infrastructure/persistence/jdbc/JdbcQuestionRepository.java
> +                    "SELECT Q.id           as 'question_id', " +
Parce que assistant, il m'a conseiller des faire des joins
La version que tu parles était ma première implémentation mais d'après ce que l'assistant m'a répondu, il vaut mieux faire des joins même c'est compliqué à gérer

2020-10-22 11:33 UTC, KurohanaJuri commented on src/main/java/ch/heigvd/amt/mvcProject/ui/web/question/handler/AnswerHandler.java
> +        for (Cookie cookie : cookies) {
J'ai pas pensé qu'on pouvait utiliser les sessions

2020-10-22 11:33 UTC, KurohanaJuri commented on src/main/java/ch/heigvd/amt/mvcProject/ui/web/question/handler/NewQuestionRequestHandler.java
> +                .username(currentUserDTO.getUsername())
Oublie de ma part, les vote sont pas là

2020-10-22 11:33 UTC, KurohanaJuri commented on src/main/webapp/WEB-INF/views/question.jsp
> +<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
Pour formatter la date

2020-10-22 11:33 UTC, KurohanaJuri commented on src/test/java/ch/heigvd/amt/mvcProject/application/answer/AnswerFacadeTestIT.java
> +
Bien vu, je vais ajouter

2020-10-22 11:33 UTC, KurohanaJuri commented on src/test/java/ch/heigvd/amt/mvcProject/application/question/QuestionFacadeTestIT.java
> +    public void A_GetQuestionWhenEmptyReturnEmptyList() {
Ouais mais je pense que je vais de toute façon tout delete à chaque test

2020-10-22 11:33 UTC, KurohanaJuri commented on src/test/java/ch/heigvd/amt/mvcProject/domain/answer/AnswerTest.java
> +                .id(new AnswerId())
Oups

2020-10-22 12:08 UTC, KurohanaJuri commented on src/main/java/ch/heigvd/amt/mvcProject/application/question/QuestionsDTO.java
> +        private String username;
Hum on a toujours besoin du nom pour l'affichage et l'id n'est pas nécessaire pour la DTO non ?

2020-10-22 12:08 UTC, KurohanaJuri commented on src/main/java/ch/heigvd/amt/mvcProject/domain/answer/Answer.java
> +    @Setter(AccessLevel.NONE)
Je comprends pas ^^"

2020-10-22 12:08 UTC, KurohanaJuri commented on src/main/java/ch/heigvd/amt/mvcProject/infrastructure/persistence/jdbc/JdbcQuestionRepository.java
> +                    "SELECT Q.id           as 'question_id', " +
Et avec deux facade, tu fais deux accès à la db, alors qu'avec un join, il y a une seul requête.
Tu peux filtreer pour qu'elle te retourne uniquement les données utilies

2020-10-24 10:34 UTC, BPotet approved these changes

2020-10-24 10:34 UTC, merged