Fb comments
amtteamheig/amt_project pull request #52
Opened 2020-10-25 12:30 UTC by KurohanaJuri

Now user can comment on a question or an answer \o/

2020-10-25 16:42 UTC, BPotet requested changes

2020-10-25 16:42 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/application/comment/CommentFacade.java
> +                        .orElseThrow(() -> new QuestionFailedException(
Pourquoi Question et pas plutôt CommentFailedException ?

2020-10-25 16:42 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/application/comment/CommentFacade.java
> +                        .orElseThrow(() -> new AnswerFailedException(
Même remarque, c'est surtout parce que t'es dans la CommentFacade

2020-10-25 16:42 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/application/question/QuestionFacade.java
> +                    .answersDTO(AnswersDTO.builder().answers(new ArrayList<>()).build())
Ou rien aussi, ça va x) Puisque answers() crée un arrayList() si c'est vide

2020-10-25 16:42 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/ui/web/question/QuestionRenderer.java
> +        } catch (QuestionFailedException | CommentFailedException | AnswerFailedException e) {
Du coup c'est BusinessException à ce moment

2020-10-25 16:42 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/ui/web/question/handler/AnswerHandler.java
> +        } catch (AnswerFailedException | UserFailedException | QuestionFailedException | CommentFailedException e) {
Même remarque

2020-10-25 16:42 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/ui/web/question/handler/CommentHandler.java
> +            e.printStackTrace();
Mais pourquoi printStackTrace xD On va laisser l'utilisateur avec un truc hyper moche si il y a une erreur x) ?

2020-10-25 16:42 UTC, BPotet commented on src/main/webapp/WEB-INF/views/fragments/answer.jsp
> +                    <a href="javascript:void(0)" class="p-2 btn-link" onclick="toggleVisibility('add-comment-container-${answer.id}' )">Add comment</a>
Qu'est-ce-que c'est que ça ._. Mais pourquoi pas simplement
```html
<btn></btn>
```

2020-10-25 16:42 UTC, BPotet commented on src/test/java/ch/heigvd/amt/mvcProject/domain/comment/CommentTest.java
> +
Il manquerait juste un test que si userId est vide ou questionId est vide ou answerId est vide, ça devrait te cracher. Mais il manque aussi juste le test que si questionId et answerId sont présents, alors ça devrait aussi te cracher dessus. Et finalement le cas trivial si answerId est présent, alors ça devrait deepClone x)

2020-10-25 16:43 UTC, KurohanaJuri commented on src/main/java/ch/heigvd/amt/mvcProject/application/comment/CommentFacade.java
> +                        .orElseThrow(() -> new QuestionFailedException(
par ce que la question n'est pas trouvé

2020-10-25 16:43 UTC, KurohanaJuri commented on src/main/java/ch/heigvd/amt/mvcProject/application/comment/CommentFacade.java
> +                        .orElseThrow(() -> new AnswerFailedException(
Oui mais c'est l'id de la response qui n'est pas trouvé

2020-10-25 16:45 UTC, KurohanaJuri commented on src/test/java/ch/heigvd/amt/mvcProject/domain/comment/CommentTest.java
> +
Alors les check sur l'id que question et answer ca crée une dépende cyclique et on est doom

2020-10-28 19:03 UTC, BPotet approved these changes

2020-10-28 19:03 UTC, BPotet commented on src/main/java/ch/heigvd/amt/mvcProject/ui/web/question/handler/CommentHandler.java
> +        String questionId = req.getParameter("comment_question_id");
Pourquoi pas simplement faire comme AnswerId ?

2020-10-28 21:35 UTC, merged